name: magora vdiffr output

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '40 * * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('Sage-Bionetworks/magora', ref = remotes::github_pull(22))"
          Rscript -e "install.packages('vdiffr')"
      - name: Run script
        run: |-
          Rscript -e "source('plot.R')"
      - name: Commit results
        run: |
          git config --global user.email "sharla.gelfand@gmail.com"
          git config --global user.name "sharlagelfand"
          git commit -m "Add the plot svg" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
